#!/bin/sh

apt-get install -y python3 python3-dev python3-pip


if [ -d "/root/arpjet/debug/" ]; then
    echo "Found debug environment";
    bash /root/arpjet/debug/start.sh;
else 
    echo "Setting up debug environment";
    mkdir -p /root/arpjet/;
    cd /root/arpjet/;
    git clone arpjet.git debug --recursive;
    service arpjet restart;
fi